FROM node:20-alpine AS builder
WORKDIR /app
COPY app/package*.json ./
RUN npm install --force
COPY app/ .
RUN npm run build

FROM nginx:alpine
RUN rm -f /usr/share/nginx/html/* /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
