apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service-deployment
  namespace: education
  labels:
    app: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
      - name: teacher-service
        image: eline2016/devopspfe-teacher-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3007
        env:
        - name: PORT
          value: "3007"
        - name: HOST
          value: "0.0.0.0"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "education"
