apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: education

commonLabels:
  app.kubernetes.io/name: horizons-tsa
  app.kubernetes.io/version: v1

resources:
  # Configuration & Security
  - configmap.yaml
  - rbac.yaml
  - network-policies.yaml
  
  # Database
  - database/postgres.yaml
  
  # Backend Microservices
  - backend/auth-service.yaml
  - backend/user-service.yaml
  - backend/activity-service.yaml
  - backend/classroom-service.yaml
  - backend/parent-service.yaml
  - backend/student-service.yaml
  - backend/teacher-service.yaml
  - backend/gateway-backend.yaml
  
  # Frontend
  - frontend/frontend-app.yaml
  
  # Monitoring
  - monitoring/prometheus-deployment.yaml
  - monitoring/grafana-deployment.yaml
  
  # Logging & Messaging
  - logging-messaging/elasticsearch-kibana-rabbitmq.yaml
