#!/bin/bash
# Quick Access Guide for DevOps PFE Project

echo "🎯 DEVOPS PFE - QUICK ACCESS"
echo "========================================"
echo ""
echo "📱 Frontend"
echo "URL: http://localhost:31927"
echo "Email: admin@school.com"
echo "Password: admin12345"
echo ""
echo "🔐 Argo CD"
echo "URL: http://localhost:32000"
echo "Username: admin"
echo "Password: $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d 2>/dev/null || echo 'RUN: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath \"{.data.password}\" | base64 -d')"
echo ""
echo "🗄️  Database"
echo "Host: localhost"
echo "Port: 5432"
echo "User: education_user"
echo "Password: education_password_secure_123"
echo ""
echo "⚙️  Services"
echo "Gateway:    http://gateway:3000"
echo "Student:    http://student-service:3005"
echo "Parent:     http://parent-service:3004"
echo "Classroom:  http://classroom-service:3006"
echo "Activity:   http://activity-service:3003"
echo "Auth:       http://auth-service:3001"
echo "User:       http://user-service:3002"
echo "Teacher:    http://teacher-service:3007"
echo ""
echo "📊 Kubernetes Status"
kubectl get pods -n education --no-headers | wc -l | xargs echo "Total pods in education namespace:"
kubectl get pods -n argocd --no-headers | wc -l | xargs echo "Total pods in argocd namespace:"
echo ""
echo "✅ All systems ready!"
